#!/usr/bin/env bash
# Highlander

# Disable buffering (if needed for the checker)
export STDOUT=$(which stdbuf)

# Trap SIGTERM
trap 'echo "I am invincible!!!"' SIGTERM

while true
do
  echo "To infinity and beyond"
  sleep 2
done
