#!/usr/bin/env bash
# This script forcefully kills all instances of the 7-highlander process

# Find all PIDs of 7-highlander and kill them with SIGKILL
pgrep -f "7-highlander" | while read -r pid; do
  kill -9 "$pid"
done
